// vue/src/components/ImageResizer.vue
<template>
    <div class="w-full space-y-4">
        <form class="space-y-4" @submit="onResize">
            <div class="flex items-center justify-center w-full">
                <label for="dropzone-file"
                    class="flex flex-col items-center justify-center w-full h-40 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 hover:bg-gray-100">
                    <div class="flex flex-col items-center justify-center pt-5 pb-6">
                        <svg class="w-8 h-8 mb-4 text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                            fill="none" viewBox="0 0 20 16">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2" />
                        </svg>
                        <p class="mb-2 text-sm text-gray-500">
                            <span class="font-semibold">Click to upload</span>
                        </p>
                        <p class="text-xs text-gray-500">
                            SVG, PNG, JPG or GIF (MAX. 800x400px)
                        </p>
                    </div>
                    <input id="dropzone-file" type="file" class="hidden"
                        @change="(e: any) => { onFileSelect(e.target.files) }" />
                </label>
            </div>

            <div class="flex items-center gap-8">
                <NumberInput title="Width" class="w-1/2" :value="toWidthScaleString" :handleChange="onWidthSizeChange" />
                <NumberInput title="Height" class="w-1/2" :value="toHeightScaleString" :handleChange="onHeightSizeChange" />
                <CheckBox />
                <ResizeButton />
            </div>
            <hr>
        </form>
        <!-- <div class="rounded space-y-2">
                <p class="font-medium">Resized</p>
                <img v-if="workingImgSize && resizedImgSrc" :src="resizedImgSrc" :width="workingImgSize.w"
                    :height="workingImgSize.h" alt="Resized" class="w-full" />
            </div> -->
        <FadeIn :class="['w-full mb-6 space-y-4', resizedImgSrc || !energyMap ? 'hidden' : '']">
            <p class="font-medium">Resized Image</p>
            <div className="w-full overflow-scroll">
                <canvas ref="canvasRef"></canvas>
                <div v-if="workingImgSize && seams" :style="{ marginTop: `-${workingImgSize.h}px` }">
                    <Seams :seams="seams" :width="workingImgSize.w" :height="workingImgSize.h" />
                </div>
            </div>
        </FadeIn>
        <div class="rounded space-y-2" v-if="workingImgSize && energyMap">
            <!-- <EnergyMap :energyMap="energyMap" :width="workingImgSize.w" :height="workingImgSize.h" /> -->
            <!-- {seamsCanvas} -->
        </div>
        <div class="w-full rounded space-y-2">
            <div class="flex items-center gap-2">
                <p class="font-medium">Original</p>
                <div v-if="originalImgSize" className="text-xs text-gray-600 whitespace-nowrap">
                    {{ `${originalImgSize.w} x ${originalImgSize.h} px` }}
                </div>
            </div>
            <img :src="imageSrc" alt="Original" ref="imgRef" class="w-full" />
        </div>
    </div>

    <!-- <div v-if="imgAuthor && imgAuthorURL" class="text-xs text-gray-400 mt-2 flex justify-center items-center font-light">
        <div class="mr-1">Photo by</div>
        <a :href="imgAuthorURL" style="color: #aaa; font-weight: 300;" target="_blank" rel="noreferrer">
            {{ imgAuthor }}
        </a>
    </div> -->

    <div v-if="props.withSeam && workingImgSize && seams" :style="{ marginTop: `-${workingImgSize.h}px` }">
        <Seams :seams="seams" :width="workingImgSize.w" :height="workingImgSize.h" />
    </div>

    <!-- <span v-if="workingImgSize?.w && originalImgViewSize?.w && workingImgSize.w > originalImgViewSize.w"
        className="text-xs text-gray-400 ml-4">↔︎ scrollable</span> -->
</template>
  
<script lang="ts" setup>
import { ref, watchEffect } from 'vue'
import defaultImgSrc from '../assets/02.jpg'
import {
    EnergyMap as EnergyMapType,
    Seam,
    OnIterationArgs,
    ImageSize,
    resizeImage,
    ALPHA_DELETE_THRESHOLD,
    MAX_WIDTH_LIMIT,
    MAX_HEIGHT_LIMIT,
} from '../utils/contentAwareResizer'
import { Coordinate, getPixel, setPixel } from '../utils/image';
import FileSelector from './FileSelector.vue';
import ButtonPrimary from './button/ButtonPrimary.vue';
import NumberInput from './input/NumberInput.vue';
import ResizeButton from './button/ResizeButton.vue';
import CheckBox from './input/CheckBox.vue';
import EnergyMap from './EnergyMap.vue';
import Seams from './Seams.vue';
import FadeIn from './FadeIn.vue';

const defaultWidthScale = 50;
const defaultHeightScale = 70;
const minScale = 1;
const maxScale = 100;
const maxWidthLimit = MAX_WIDTH_LIMIT;
const maxHeightLimit = MAX_HEIGHT_LIMIT;

type ImageResizerProps = {
    withSeam?: boolean
    withEnergyMap?: boolean
};

const props = defineProps<ImageResizerProps>()

const imgAuthor = ref<string | null>('ian dooley');
const imgAuthorURL = ref<string | null>(
    'https://unsplash.com/@sadswim?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText',
);
const useNaturalSize = ref<boolean>(false);
const imageSrc = ref<string>(defaultImgSrc);
const resizedImgSrc = ref<string | null>(null);
const energyMap = ref<EnergyMapType | null>(null);
const originalImgSize = ref<ImageSize | null>(null);
const originalImgViewSize = ref<ImageSize | null>(null);
const workingImgSize = ref<ImageSize | null>(null);
const seams = ref<Seam[] | null>(null);
const isResizing = ref<boolean>(false);
const progress = ref<number>(0);
const maskImgData = ref<ImageData | null>(null);
const maskRevision = ref<number>(0);
const toWidthScale = ref<number>(defaultWidthScale);
const toWidthScaleString = ref<string | undefined>(`${defaultWidthScale}`);
const toHeightScale = ref<number>(defaultHeightScale);
const toHeightScaleString = ref<string | undefined>(`${defaultHeightScale}`);

const imgRef = ref<HTMLImageElement | null>(null);
const canvasRef = ref<HTMLCanvasElement | null>(null);

const onUseOriginalSizeChange = (state: boolean): void => {
    useNaturalSize.value = state
};

const onReset = (): void => {
    resizedImgSrc.value = null;
    seams.value = null;
    workingImgSize.value = null;
    energyMap.value = null;
    progress.value = 0;
    originalImgViewSize.value = null;
};

const onFileSelect = (files: FileList | null): void => {
    console.log(files)
    if (!files || !files.length) {
        return;
    }
    imgAuthor.value = null;
    imgAuthorURL.value = null;
    onReset();
    const imageURL = URL.createObjectURL(files[0]);
    imageSrc.value = imageURL;
};

const onWidthSizeChange = (size: string | undefined): void => {
    const radix = 10;
    const scale = Math.max(Math.min(parseInt(size || '0', radix), maxScale), minScale);
    if (size) {
        toWidthScaleString.value = `${scale}`;
    } else {
        toWidthScaleString.value = size;
    }
    toWidthScale.value = scale
};

const onHeightSizeChange = (size: string | undefined): void => {
    const radix = 10;
    const scale = Math.max(Math.min(parseInt(size || '0', radix), maxScale), minScale);
    if (size) {
        toHeightScaleString.value = `${scale}`
    } else {
        toHeightScaleString.value = size
    }
    toHeightScale.value = scale
};

const onFinish = (): void => {
    if (!canvasRef.value) {
        return;
    }
    const imageType = 'image/png';
    canvasRef.value.toBlob((blob: Blob | null): void => {
        if (!blob) {
            return;
        }
        const imgUrl = URL.createObjectURL(blob);
        resizedImgSrc.value = imgUrl
        isResizing.value = false
    }, imageType);
};

const onClearMask = (): void => {
    maskRevision.value = maskRevision.value + 1;
};

const onMaskDrawEnd = (imgData: ImageData): void => {
    maskImgData.value = imgData
};

const applyMask = (img: ImageData): void => {
    if (!maskImgData.value) {
        return;
    }

    const wRatio = maskImgData.value.width / img.width;
    const hRatio = maskImgData.value.height / img.height;

    const imgXYtoMaskXY = ({ x: imgX, y: imgY }: Coordinate): Coordinate => {
        return {
            x: Math.floor(imgX * wRatio),
            y: Math.floor(imgY * hRatio),
        };
    };

    for (let y = 0; y < img.height; y += 1) {
        for (let x = 0; x < img.width; x += 1) {
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            const [mR, mG, mB, mA] = getPixel(
                maskImgData.value,
                imgXYtoMaskXY({ x, y }),
            );
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            const [iR, iG, iB, iA] = getPixel(img, { x, y });
            if (mA) {
                setPixel(img, { x, y }, [iR, iG, iB, ALPHA_DELETE_THRESHOLD]);
            }
        }
    }
};

const onIteration = async (args: OnIterationArgs): Promise<void> => {
    const {
        seam,
        img,
        energyMap: nrgMap,
        size: { w, h },
        step,
        steps,
    } = args;

    const canvas: HTMLCanvasElement | null = canvasRef.value;
    if (!canvas) {
        return;
    }

    canvas.width = w;
    canvas.height = h;

    const ctx: CanvasRenderingContext2D | null = canvas.getContext('2d');
    if (!ctx) {
        return;
    }

    ctx.putImageData(img, 0, 0, 0, 0, w, h);

    energyMap.value = nrgMap
    seams.value = [seam]
    workingImgSize.value = { w, h }
    progress.value = step / steps
};

const onResize = (e: Event): void => {
    e.preventDefault();

    const srcImg: HTMLImageElement | null = imgRef.value;
    if (!srcImg) return;

    const canvas: HTMLCanvasElement | null = canvasRef.value;
    if (!canvas) return;


    onReset();
    isResizing.value = true

    let w = useNaturalSize ? srcImg.naturalWidth : srcImg.width;
    let h = useNaturalSize ? srcImg.naturalHeight : srcImg.height;
    const ratio = w / h;

    originalImgViewSize.value = {
        w: srcImg.width,
        h: srcImg.height,
    }

    if (w > maxWidthLimit) {
        w = maxWidthLimit;
        h = Math.floor(w / ratio);
    }

    if (h > maxHeightLimit) {
        h = maxHeightLimit;
        w = Math.floor(h * ratio);
    }

    canvas.width = w;
    canvas.height = h;

    console.log(canvas);

    const ctx: CanvasRenderingContext2D | null = canvas.getContext('2d');
    if (!ctx) {
        return;
    }

    ctx.drawImage(srcImg, 0, 0, w, h);

    const img: ImageData = ctx.getImageData(0, 0, w, h);

    applyMask(img);

    const toWidth = Math.floor((toWidthScale.value * w) / 100);
    const toHeight = Math.floor((toHeightScale.value * h) / 100);

    resizeImage({
        img,
        toWidth,
        toHeight,
        onIteration,
    }).then(() => {
        onFinish();
    });
}

watchEffect(() => {
    const srcImg: HTMLImageElement | null = imgRef.value;
    if (!srcImg) {
        return;
    }
    srcImg.addEventListener('load', () => {
        if (!imgRef.value) {
            return;
        }
        originalImgSize.value = {
            w: imgRef.value.naturalWidth,
            h: imgRef.value.naturalHeight,
        }
        originalImgViewSize.value = {
            w: imgRef.value.width,
            h: imgRef.value.height,
        }
    });
});

watchEffect(() => {
    function updateSize(): void {
        if (!imgRef.value) {
            return;
        }
        originalImgViewSize.value = {
            w: imgRef.value.width,
            h: imgRef.value.height,
        }
    }
    window.addEventListener('resize', updateSize);
    return (): void => {
        window.removeEventListener('resize', updateSize);
    };
});

const canImage = new Image()
canImage.src = imageSrc.value
canImage.onload = function () {
    // ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
};
</script>

// vite-react/src/components/ImageResizer.tsx
import React, { useEffect, useRef, useState } from 'react';
import { ImShrink2 } from 'react-icons/im';
import { FaRegHandPointer } from 'react-icons/fa';

import {
  EnergyMap as EnergyMapType,
  Seam,
  OnIterationArgs,
  ImageSize,
  resizeImage,
  ALPHA_DELETE_THRESHOLD,
  MAX_WIDTH_LIMIT,
  MAX_HEIGHT_LIMIT,
} from '../utils/contentAwareResizer';
import EnergyMap from './EnergyMap';
import Seams from './Seams';
import defaultImgSrc from '../assets/02.jpg';
import Button, { BUTTON_KIND_SECONDARY } from './Button';
import FileSelector from './FileSelector';
import Checkbox from './Checkbox';
import Progress from './Progress';
import Input from './Input';
import FadeIn from './FadeIn';
import Mask from './Mask';
import { Coordinate, getPixel, setPixel } from '../utils/image';
import { MdLayersClear } from 'react-icons/md';

const defaultWidthScale = 50;
const defaultHeightScale = 70;
const minScale = 1;
const maxScale = 100;
const maxWidthLimit = MAX_WIDTH_LIMIT;
const maxHeightLimit = MAX_HEIGHT_LIMIT;

type ImageResizerProps = {
  withSeam?: boolean,
  withEnergyMap?: boolean,
};

const ImageResizer = (props: ImageResizerProps): React.ReactElement => {
  const {
    withSeam = false,
    withEnergyMap = false,
  } = props;

  const [imgAuthor, setImgAuthor] = useState<string | null>('ian dooley');
  const [imgAuthorURL, setImgAuthorURL] = useState<string | null>(
    'https://unsplash.com/@sadswim?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText',
  );

  const [useNaturalSize, setUseNaturalSize] = useState<boolean>(false);
  const [imageSrc, setImageSrc] = useState<string>(defaultImgSrc);
  const [resizedImgSrc, setResizedImgSrc] = useState<string | null>(null);
  const [energyMap, setEnergyMap] = useState<EnergyMapType | null>(null);
  const [originalImgSize, setOriginalImgSize] = useState<ImageSize | null>(null);
  const [originalImgViewSize, setOriginalImgViewSize] = useState<ImageSize | null>(null);
  const [workingImgSize, setWorkingImgSize] = useState<ImageSize | null>(null);
  const [seams, setSeams] = useState<Seam[] | null>(null);
  const [isResizing, setIsResizing] = useState<boolean>(false);
  const [progress, setProgress] = useState<number>(0);
  const [maskImgData, setMaskImgData] = useState<ImageData | null>(null);
  const [maskRevision, setMaskRevision] = useState<number>(0);
  const [toWidthScale, setToWidthScale] = useState<number>(defaultWidthScale);
  const [toWidthScaleString, setToWidthScaleString] = useState<string | undefined>(`${defaultWidthScale}`);
  const [toHeightScale, setToHeightScale] = useState<number>(defaultHeightScale);
  const [toHeightScaleString, setToHeightScaleString] = useState<string | undefined>(`${defaultHeightScale}`);

  const imgRef = useRef<HTMLImageElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const onUseOriginalSizeChange = (state: boolean): void => {
    setUseNaturalSize(state);
  };

  const onReset = (): void => {
    setResizedImgSrc(null);
    setSeams(null);
    setWorkingImgSize(null);
    setEnergyMap(null);
    setProgress(0);
    setOriginalImgViewSize(null);
  };

  const onFileSelect = (files: FileList | null): void => {
    if (!files || !files.length) {
      return;
    }
    setImgAuthor(null);
    setImgAuthorURL(null);
    onReset();
    const imageURL = URL.createObjectURL(files[0]);
    setImageSrc(imageURL);
  };

  const onWidthSizeChange = (size: string | undefined): void => {
    const radix = 10;
    const scale = Math.max(Math.min(parseInt(size || '0', radix), maxScale), minScale);
    if (size) {
      setToWidthScaleString(`${scale}`);
    } else {
      setToWidthScaleString(size);
    }
    setToWidthScale(scale);
  };

  const onHeightSizeChange = (size: string | undefined): void => {
    const radix = 10;
    const scale = Math.max(Math.min(parseInt(size || '0', radix), maxScale), minScale);
    if (size) {
      setToHeightScaleString(`${scale}`);
    } else {
      setToHeightScaleString(size);
    }
    setToHeightScale(scale);
  };

  const onFinish = (): void => {
    if (!canvasRef.current) {
      return;
    }
    const imageType = 'image/png';
    canvasRef.current.toBlob((blob: Blob | null): void => {
      if (!blob) {
        return;
      }
      const imgUrl = URL.createObjectURL(blob);
      setResizedImgSrc(imgUrl);
      setIsResizing(false);
    }, imageType);
  };

  const onClearMask = (): void => {
    setMaskRevision(maskRevision + 1);
  };

  const onMaskDrawEnd = (imgData: ImageData): void => {
    setMaskImgData(imgData);
  };

  const applyMask = (img: ImageData): void => {
    if (!maskImgData) {
      return;
    }

    const wRatio = maskImgData.width / img.width;
    const hRatio = maskImgData.height / img.height;

    const imgXYtoMaskXY = ({ x: imgX, y: imgY }: Coordinate): Coordinate => {
      return {
        x: Math.floor(imgX * wRatio),
        y: Math.floor(imgY * hRatio),
      };
    };

    for (let y = 0; y < img.height; y += 1) {
      for (let x = 0; x < img.width; x += 1) {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const [mR, mG, mB, mA] = getPixel(
          maskImgData,
          imgXYtoMaskXY({ x, y }),
        );
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const [iR, iG, iB, iA] = getPixel(img, { x, y });
        if (mA) {
          setPixel(img, { x, y }, [iR, iG, iB, ALPHA_DELETE_THRESHOLD]);
        }
      }
    }
  };

  const onIteration = async (args: OnIterationArgs): Promise<void> => {
    const {
      seam,
      img,
      energyMap: nrgMap,
      size: { w, h },
      step,
      steps,
    } = args;

    const canvas: HTMLCanvasElement | null = canvasRef.current;
    if (!canvas) {
      return;
    }

    canvas.width = w;
    canvas.height = h;

    const ctx: CanvasRenderingContext2D | null = canvas.getContext('2d');
    if (!ctx) {
      return;
    }

    ctx.putImageData(img, 0, 0, 0, 0, w, h);

    setEnergyMap(nrgMap);
    setSeams([seam]);
    setWorkingImgSize({ w, h });
    setProgress(step / steps);
  };

  const onResize = (): void => {
    const srcImg: HTMLImageElement | null = imgRef.current;
    if (!srcImg) {
      return;
    }
    const canvas: HTMLCanvasElement | null = canvasRef.current;
    if (!canvas) {
      return;
    }

    onReset();
    setIsResizing(true);

    let w = useNaturalSize ? srcImg.naturalWidth : srcImg.width;
    let h = useNaturalSize ? srcImg.naturalHeight : srcImg.height;
    const ratio = w / h;

    setOriginalImgViewSize({
      w: srcImg.width,
      h: srcImg.height,
    });

    if (w > maxWidthLimit) {
      w = maxWidthLimit;
      h = Math.floor(w / ratio);
    }

    if (h > maxHeightLimit) {
      h = maxHeightLimit;
      w = Math.floor(h * ratio);
    }

    canvas.width = w;
    canvas.height = h;

    const ctx: CanvasRenderingContext2D | null = canvas.getContext('2d');
    if (!ctx) {
      return;
    }

    ctx.drawImage(srcImg, 0, 0, w, h);

    const img: ImageData = ctx.getImageData(0, 0, w, h);

    applyMask(img);

    const toWidth = Math.floor((toWidthScale * w) / 100);
    const toHeight = Math.floor((toHeightScale * h) / 100);

    resizeImage({
      img,
      toWidth,
      toHeight,
      onIteration,
    }).then(() => {
      onFinish();
    });
  };

  useEffect(() => {
    const srcImg: HTMLImageElement | null = imgRef.current;
    if (!srcImg) {
      return;
    }
    srcImg.addEventListener('load', () => {
      if (!imgRef.current) {
        return;
      }
      setOriginalImgSize({
        w: imgRef.current.naturalWidth,
        h: imgRef.current.naturalHeight,
      });
      setOriginalImgViewSize({
        w: imgRef.current.width,
        h: imgRef.current.height,
      });
    });
  }, []);

  useEffect(() => {
    function updateSize(): void {
      if (!imgRef.current) {
        return;
      }
      setOriginalImgViewSize({
        w: imgRef.current.width,
        h: imgRef.current.height,
      });
    }
    window.addEventListener('resize', updateSize);
    return (): void => {
      window.removeEventListener('resize', updateSize);
    };
  }, []);

  const imgAuthorLink = imgAuthor && imgAuthorURL ? (
    <div className="text-xs text-gray-400 mt-2 flex justify-center items-center font-light">
      <div className="mr-1">
        Photo by
      </div>
      <a
        href={imgAuthorURL}
        style={{ color: '#aaa', fontWeight: 300 }}
        target="_blank"
        rel="noreferrer"
      >
        {imgAuthor}
      </a>
    </div>
  ) : null;

  const seamsCanvas = withSeam && workingImgSize && seams ? (
    <div style={{ marginTop: `-${workingImgSize.h}px` }}>
      <Seams seams={seams} width={workingImgSize.w} height={workingImgSize.h} />
    </div>
  ) : null;

  const originalImageSizeText = originalImgSize ? (
    <sup className="text-xs text-gray-400 whitespace-nowrap">
      {`${originalImgSize.w} x ${originalImgSize.h} px`}
    </sup>
  ) : null;

  const maskControls = (
    <div>
      <Button
        onClick={onClearMask}
        disabled={isResizing || !maskImgData}
        kind={BUTTON_KIND_SECONDARY}
        title="Clear mask"
        className="rounded-full"
        style={{ padding: '8px 8px', border: 0, outline: 'none' }}
      >
        <MdLayersClear size={16} />
      </Button>
    </div>
  );

  const mask = originalImgViewSize ? (
    <div className="flex flex-col" style={{ marginTop: `-${originalImgViewSize.h}px` }}>
      <Mask
        width={originalImgViewSize.w}
        height={originalImgViewSize.h}
        disabled={isResizing}
        onDrawEnd={onMaskDrawEnd}
        revision={maskRevision}
      />
      <div className="flex flex-row justify-end" style={{ marginTop: '-36px', zIndex: 100 }}>
        <div className="mr-1">
          {maskControls}
        </div>
      </div>
    </div>
  ) : null;

  const originalImage = (
    <FadeIn>
      <div className="flex flex-row justify-center items-center mb-1 sm:mb-0">
        <div className="flex-1 sm:flex sm:flex-row sm:items-center">
          <div className="sm:flex-1">
            <b>Original image</b> {originalImageSizeText}
          </div>
          <div className="text-xs text-gray-400 flex flex-row items-center justify-self-end">
            <div className="mr-1">
              <FaRegHandPointer size={12} />
            </div>
            <div>
              Mask to remove
            </div>
          </div>
        </div>
      </div>
      <img src={imageSrc} alt="Original" ref={imgRef} style={{ margin: 0 }} />
      {mask}
      {imgAuthorLink}
    </FadeIn>
  );

  const workingImageScrollableText = (
    workingImgSize?.w && originalImgViewSize?.w && workingImgSize.w > originalImgViewSize.w
  ) ? <span className="text-xs text-gray-400 ml-4">↔︎ scrollable</span> : null;

  const workingImageSizeText = workingImgSize ? (
    <sup className="text-xs text-gray-400 whitespace-nowrap">
      {`${workingImgSize.w} x ${workingImgSize.h} px`}
    </sup>
  ) : null;

  const workingImage = (
    <FadeIn className={`mb-6 ${resizedImgSrc || !energyMap ? 'hidden' : ''}`}>
      <div><b>Resized image</b> {workingImageSizeText} {workingImageScrollableText}</div>
      <div className="overflow-scroll">
        <canvas ref={canvasRef} />
        {seamsCanvas}
      </div>
    </FadeIn>
  );

  const resultImageSizeText = workingImgSize ? (
    <sup className="text-xs text-gray-400 whitespace-nowrap">
      {`${workingImgSize.w} x ${workingImgSize.h} px`}
    </sup>
  ) : null;

  const resultImage = workingImgSize && resizedImgSrc ? (
    <FadeIn className="mb-6">
      <div><b>Resized image</b> {resultImageSizeText}</div>
      <img src={resizedImgSrc} width={workingImgSize.w} height={workingImgSize.h} alt="Resized" style={{ margin: 0 }} />
    </FadeIn>
  ) : null;

  const debugEnergyMap = withEnergyMap && workingImgSize ? (
    <FadeIn className="mb-6">
      <div><b>Energy map</b></div>
      <EnergyMap energyMap={energyMap} width={workingImgSize.w} height={workingImgSize.h} />
      {seamsCanvas}
    </FadeIn>
  ) : null;

  const resizerControls = (
    <div className="flex flex-col justify-start items-start mb-1">

      <div className="mb-3 flex flex-row">
        <div className="mr-2">
          <FileSelector
            onSelect={onFileSelect}
            disabled={isResizing}
            accept="image/png,image/jpeg"
          >
            Choose image
          </FileSelector>
        </div>

        <div>
          <Button
            onClick={onResize}
            disabled={isResizing || !toWidthScaleString}
            startEnhancer={<ImShrink2 size={14} />}
          >
            Resize
          </Button>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row">
        <div className="mb-2 mr-6 flex flex-row items-center">
          <div className="text-xs mr-1">Width</div>
          <Input
            onChange={onWidthSizeChange}
            disabled={isResizing}
            // @ts-ignore
            type="number"
            min={minScale}
            max={maxScale}
            className="w-14 text-center"
            value={toWidthScaleString}
          />
          <div className="text-xs ml-1 mr-4">%</div>

          <div className="text-xs mr-1">Height</div>
          <Input
            onChange={onHeightSizeChange}
            disabled={isResizing}
            // @ts-ignore
            type="number"
            min={minScale}
            max={maxScale}
            className="w-14 text-center"
            value={toHeightScaleString}
          />
          <div className="text-xs ml-1">%</div>
        </div>

        <div className="mb-2">
          <Checkbox disabled={isResizing} onChange={onUseOriginalSizeChange}>
            <span className="text-xs">
              Higher quality <span className="text-gray-400">(takes longer)</span>
            </span>
          </Checkbox>
        </div>
      </div>

    </div>
  );

  const progressBar = (
    <div className="mb-6">
      <Progress progress={progress} />
    </div>
  );

  return (
    <>
      {resizerControls}
      {progressBar}
      {workingImage}
      {resultImage}
      {debugEnergyMap}
      {originalImage}
    </>
  );
};

export default ImageResizer;
